<?xml version="1.0" encoding="utf-8"?><Database Name="Laundry" Class="ClothDataDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=C:\Users\Daniel\OneDrive\Документы\DataBases\Laundry.mdf;Integrated Security=True;Connect Timeout=30" SettingsObjectName="LaundryManager.Properties.Settings" SettingsPropertyName="LaundryConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Cloths" Member="Cloths">
    <Type Name="Cloth">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Image" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="LastWashDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastWearDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="WashingCooldown" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CurrentCooldownState" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MaterialId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TypeId" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>